# Generated by Django 4.0.4 on 2022-05-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncup_board', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncupboard',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.team'),
        ),
    ]
