# Generated by Django 4.0.4 on 2022-05-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standup_card', '0001_initial'),
        ('syncup_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupcard',
            name='syncup_board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_card', to='syncup_board.syncupboard'),
        ),
    ]
