# Generated by Django 4.0.4 on 2022-05-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncup_board', '0002_initial'),
        ('standup_card', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standupcard',
            name='syncup_board_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standup_card', to='syncup_board.syncupboard'),
        ),
    ]
